### ISSUE TITLE
Trestle author headers validation not working properly (investigate)

### ISSUE THREAD

**Issue by AleJo2995** [oscal-compass/compliance-trestle#1508]
## Describe the bug

While running `trestle author headers` validation, it seems that the validate command is using `x-trestle-template-version` field to validate the headers against the header template under global when using `-g` parameter. That is ok if we only need to validate headers and seems to be working, but it seems to be inconsistent. What if I need to validate both header and body and the header needs to be in a different version than the current template of the document has.

e.g. template 1 points to header 1.1.0. Once i create a document out of it, I need that the header  now points to another version of the header. Should I need to switch the `header-version` field or `x-trestle-template-version`? Here comes the dilemma we need to investigate on.

## To Reproduce

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

- OS: \[e.g. iOS\]
- Python version:
- Installed packages:

**Comment by Ma1h01** [comment]
The `trestle author headers` command intends to validate the header only, according to the documentation. Therefore, users shouldn't validate both header and body with the command.

Based on the following code snippet found in `markdown_validator.py`,  the `Version` field should appear in the header instead of `header-version`.
<img width="804" alt="image" src="https://github.com/oscal-compass/compliance-trestle/assets/78010183/ebddf7dd-583e-4a30-b7b7-e43354fc4df9">

To change the version of a document, assuming there exists a template 2 containing `Version` and `x-trestle-template-version`, we should modify both `Version` and `x-trestle-template-version` in the document. If we only modify either one, the validation will fail due to the header mismatch. 
But if there is no such template 2, we need to first generate it before modifying document's version.

**Comment by AleJo2995** [comment]
This issue seem to be no longer a thing. Closing, thanks
